spring:
  datasource:
    url: jdbc:h2:file:${DB_PATH};DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
