on:
  push:
    branches:
      - main

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    name: Deploy Static Site
    steps:
      - id: Build
        run: |
          pwd
          ls -altr 
          npm install 
          npm run build
        
