on:
  push:
    branches:
      - main

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    name: Deploy Static Site
    steps:
      - run: ls -altr
      - run: npm install
      - run: npm run build
